### ISSUE TITLE
Feature Request: Highlight arbitrary days

### ISSUE THREAD

**Issue by ygt-mikekchar** [tomkp/react-calendar-pane#1]
Hi.  I've been playing with this for the last day or so.  It's the most simple and sensible react calendar component out there.  Thanks!

We need some extra functionality, so I've forked and will add it to my branch.  If you are interested, feel free to merge any of it.  I'm not sure if you want pull requests, so I'll just to the diff in my branch.

The following:
https://github.com/tomkp/react-calendar-pane/compare/master...ygt-mikekchar:day-classes

Implements the ability to arbitrarily highlight days based on a callback.  It works like:

```
let dayClasses = function(date) {
    if (some_test_on(date)) {
        return ['some', 'interesting', 'classes']
    }
    return []
}

return (
    <Calendar onSelect={this.onSelect} dayClasses={dayClasses}/>
);
```

I've updated the demo to highlight weekends using this facility.

**Comment by tomkp** [comment]
Hi

I'm glad to hear you like my component - and I'm always happy for ideas /
contributions.

Feel free to issue pull requests - I'll check them out and probably merge
them in...

Thanks

Tom

**Comment by ygt-mikekchar** [comment]
This issue is resolved by https://github.com/tomkp/react-calendar-pane/pull/4
