### ISSUE TITLE
Use custom format for "daysOfWeek"

### ISSUE THREAD

**Issue by arnaud-zg** [tomkp/react-calendar-pane#14]
Hi,

Actually, I need to use a custom format for `daysOfWeek` component. This pull request #11 seems to fix my problem.

When will the next release come?

**Comment by tomkp** [comment]
I forgot to release the latest version - thanks for letting me know!
try again now - hopefully should be working in version `1.0.4`

**Comment by arnaud-zg** [comment]
Nice, it's good for me :smiley: @fadwanassiri 
Thank you
